Import('examplesEnv')
Import('mcoreLibrary')
Import('mtmLibrary')

myEnv = examplesEnv.Clone()

sources = Split("""
                pmalloc-mt.c
                """)
myEnv.Append(CFLAGS='-DMNEMOSYNE')
myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Program('pmalloc-mt-mnemosyne.out', sources)
