Import('examplesEnv')
Import('mcoreLibrary')
Import('mtmLibrary')

myEnv = examplesEnv.Clone()

sources = Split("""
                page_density.c
                """)
myEnv.Append(CFLAGS='-DMNEMOSYNE')
myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Program('page_density-mnemosyne.out', sources)
