Import('examplesEnv')
Import('mcoreLibrary')
Import('mtmLibrary')

myEnv = examplesEnv.Clone()

sources = Split("""
                main.c
                """)

myEnv.Append(LIBS = [mcoreLibrary])
myEnv.Append(LIBS = [mtmLibrary])
myEnv.Program('simple', sources)
